-- 在 Supabase SQL 编辑器中执行，与前端表名一致。
-- 验收项录入保存：accept_item_materials
-- 移模申请列表：move_apply_list

create table if not exists public.accept_item_materials (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  base_item_id text not null,
  accept_report text default '' not null,
  material_cert text default '' not null,
  upper_mold text default '' not null,
  lower_mold text default '' not null,
  overall_mold text default '' not null,
  nameplate text default '' not null,
  length text default '' not null,
  width text default '' not null,
  height text default '' not null,
  weight text default '' not null,
  updated_at timestamptz default now() not null,
  unique (project_id, base_item_id)
);

create index if not exists idx_accept_item_materials_project on public.accept_item_materials (project_id);

create table if not exists public.move_apply_list (
  id bigint generated by default as identity primary key,
  apply_no text default '' not null,
  part_name text default '' not null,
  part_no text default '' not null,
  tool_name text default '' not null,
  from_supplier text default '' not null,
  to_supplier text default '' not null,
  applicant text default '' not null,
  apply_time text default '' not null,
  status text default 'draft' not null,
  meta jsonb default '{}'::jsonb not null,
  details jsonb default '[]'::jsonb not null
);

create index if not exists idx_move_apply_list_status on public.move_apply_list (status);

-- ---------------------------------------------------------------------------
-- RLS：已开启 RLS 且「没有任何策略」时，API 会返回空数据。
-- 下面为开发联调：允许使用 anon 公钥的前端执行 CRUD。
-- 上线前请改为按 auth.uid()、团队、project_id 等收紧策略，并勿把 service_role 暴露到浏览器。
-- ---------------------------------------------------------------------------

alter table public.accept_item_materials enable row level security;
alter table public.move_apply_list enable row level security;

drop policy if exists "anon_all_accept_item_materials" on public.accept_item_materials;
create policy "anon_all_accept_item_materials"
  on public.accept_item_materials
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists "anon_all_move_apply_list" on public.move_apply_list;
create policy "anon_all_move_apply_list"
  on public.move_apply_list
  for all
  to anon
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- projects：模具交付建档与列表展示用（可选；无列时前端仍可仅用 stages）
-- ---------------------------------------------------------------------------
alter table public.projects add column if not exists mold_archive_purchaser text default '' not null;
alter table public.projects add column if not exists mold_archive_related_staff text default '' not null;
alter table public.projects add column if not exists mold_archive_remark text default '' not null;
alter table public.projects add column if not exists project_start_date text default '' not null;
alter table public.projects add column if not exists project_end_date text default '' not null;
